### ISSUE TITLE
Gold fitting below cutofff

### ISSUE THREAD

**Issue by DarrenSherrell** [beamline-i24/spectrum#4]
Bad low E fit

**Comment by DarrenSherrell** [comment]
dials.python spectrum.py /dls/i24/data/2017/nr16818-47/GoldDigger_170512/Mo_empty_D2/Mo_empty_D2_4_zlayer_1.hdf5 -me 4000 -ie 17000 -me 2000 -e all -i Au Fe Ti Ni W Cu -c 0.1 -o 10

**Comment by MVAppleby** [comment]
In theory if gold were there then that peak would be possible with a minimum energy of 2000 as golds M5 edge absorbs at 2206 ev, and emits via Malpha 1 at 2122.9.

**Comment by MVAppleby** [comment]
Proposed solution, calculate the permeation of an x-ray photon through air and adjust the probability/relative intensity accordingly? Or just cut is the photon will not permeate far enough

**Comment by MVAppleby** [comment]
Potential solution:
- [x] Add new Data Lookup Table: https://physics.nist.gov/PhysRefData/XrayMassCoef/ComTab/air.html
- [x] Add default fluorescence detector distance

- [ ]  manual change option and auto update
- [x] Add calculation of probability of transmission over distance. 
- [x] Combine probability of transmission with relative intensity to get theorised intensity of emission line

- [ ] TESTESTEST
